### ISSUE TITLE
MermaidのgitGraphテキストはどのように作成する？

### ISSUE THREAD

**Issue by NakashimaShuusaku** [NakashimaShuusaku/GitHubActionsTest-General#11]
# 概要
GitHub-Scriptを使用してコメント作成する場合、`body:`項目にコメント内容を指定する。
Mermaidを使用してgitGraphを表示させるには改行なども含めたbodyの作成が必要

`npm`のymlが参考になりそう？
```yml
            let body = '## Release Manager\n\n'

            const comments = await github.paginate(github.rest.issues.listComments, { owner, repo, issue_number })
            let commentId = comments.find(c => c.user.login === 'github-actions[bot]' && c.body.startsWith(body))?.id

            body += `Release workflow run: ${workflow.html_url}\n\n#### Force CI to Update This Release\n\n`
            body += `This PR will be updated and CI will run for every non-\`chore:\` commit that is pushed to \`latest\`. `
            body += `To force CI to update this PR, run this command:\n\n`
            body += `\`\`\`\ngh workflow run release.yml -r ${REF_NAME} -R ${owner}/${repo} -f release-pr=${issue_number}\n\`\`\``
```
```yml
    steps:
      - name: Create Release PR Comment
        uses: actions/github-script@v6
        env:
          RELEASES: ${{ needs.release.outputs.releases }}
        with:
          script: |
            const releases = JSON.parse(process.env.RELEASES)
            const { runId, repo: { owner, repo } } = context
            const issue_number = releases[0].prNumber

            let body = '## Release Workflow\n\n'
            for (const { pkgName, version, url } of releases) {
              body += `- \`${pkgName}@${version}\` ${url}\n`
            }
```

<br>
<br>

# 参考
[npmのyml](https://github.com/npm/cli/blob/ef2674f6477d75b6909daee07691fd001f16ac80/.github/workflows/release.yml#L275-L289)
