### ISSUE TITLE
マージ元･先の両ブランチの名前を取得する方法

### ISSUE THREAD

**Issue by NakashimaShuusaku** [NakashimaShuusaku/GitHubActionsTest-General#9]
# 概要
`git log --graph  --pretty=oneline --all --abbrev-commit --boundary --left-right master...test`
コマンドを`GitHub Actions`で実行する際、`branchA...branchB`のbranch名を取得する必要があるため

<br>
<br>

# 方法
```yml
on:
  pull_request:
    types: [opened, closed]

jobs:
  debug:
    runs-on: windows-latest
    timeout-minutes: 3
    steps:
      - name: Print branch name
        env:
          HEAD_BRANCH_NAME: ${{github.head_ref}}
          BASE_BRANCH_NAME: ${{github.base_ref}}
        run: |
          echo $HEAD_BRANCH_NAME
          echo $BASE_BRANCH_NAME
```

試してみると、正常に取得できているようだった
![image](https://user-images.githubusercontent.com/100416642/223634887-ba05e4fe-6dc1-4177-93dd-f4c53dc41f74.png)

<br>
<br>

# 参考
[GitHub Actionsでブランチ名を扱う方法](https://qiita.com/iery/items/43b72813c394050b8bbc)
[github context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context)
<br>
<br>
